controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-arn: "{{ .Values.loadBalancerArn }}"
    type: NodePort
    externalTrafficPolicy: Local
    nodePorts:
      http: 30080
      https: 30443
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      labels:
        app: ingress-nginx
      type: ClusterIP
      port: 10254
