name: Terraform Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name fiap-soat-tech-challenge-k8s --region us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
          
      # Inicializar, validar e aplicar o Terraform para o diretório cluster
      - name: Initialize Terraform for Cluster
        working-directory: terraform/cluster
        run: terraform init

      - name: Validate Terraform for Cluster
        working-directory: terraform/cluster
        run: terraform validate

      - name: Plan Terraform for Cluster
        working-directory: terraform/cluster
        run: terraform plan -out=tfplan

      - name: Apply Terraform for Cluster
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/cluster
        run: terraform apply -auto-approve tfplan

      # Inicializar, validar e aplicar o Terraform para o diretório infra
      - name: Initialize Terraform for Infra
        working-directory: terraform/infra
        run: terraform init

      - name: Validate Terraform for Infra
        working-directory: terraform/infra
        run: terraform validate

      - name: Plan Terraform for Infra
        working-directory: terraform/infra
        run: terraform plan -out=tfplan-infra

      - name: Apply Terraform for Infra
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/infra
        run: terraform apply -auto-approve tfplan-infra
